# Generated by Django 6.0 on 2025-12-15 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('self_contained', models.BooleanField(default=False, help_text='Does the unit have its own bathroom/toilet?')),
                ('toilet_type', models.CharField(choices=[('PITLATRINE', 'Pitlatrine'), ('FLUSHABLE', 'Flushable'), ('TOILETPAN', 'Toilet Pan')], default='PITLATRINE', max_length=12)),
                ('water_onsite', models.BooleanField(default=False)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('RENT', 'For Rent'), ('SALE', 'For Sale')], default='SALE', help_text='Is this property for Rent or Sale?', max_length=4)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-list_date'],
            },
        ),
    ]
